#====================
#= Secrets
#====================
variables: secrets.yml

#====================
#= Web UI
#====================
web_server:
  run_v2: true
  port: 9092

#====================
#= Templates
#====================
templates:

  global:
    verify_ssl_certificates: no

  #====================
  #= Template: Transmission connection settings
  #====================
  transmission:
    transmission:
      host: localhost
      port: 9091
      #username: {? transmission.username ?}
      #password: {? transmission.password ?}
    pathscrub: windows

  #====================
  #= Template: TV-Shows
  #====================
  tvshows:
    quality: 720p+ webrip+ h264
    #trakt_lookup: yes
    thetvdb_lookup: yes
    set:
      path: '/Alexandria/TV-Series/{{series_name}}/Season {{series_season}}'
      propers: yes
    series:
      - 2 Broke Girls
      - American Gods:
          quality: webdl
      #- Archer:
      #    quality: 1080p webdl|webrip
      - Atlanta:
          quality: 1080p webdl|webrip
      - Barry:
          quality: 1080p webdl|webrip
      - Brooklyn Nine-Nine:
          quality: 1080p webdl|webrip
      - Community
      - Counterpart:
          quality: 1080p webdl|webrip
      - Divorce (2016):
          quality: 1080p webdl|webrip
      - Elementary:
          quality: 1080p webdl|webrip
#      - Fargo:
#          quality: 1080p webdl|webrip
      - Game of Thrones:
          quality: 1080p webdl|webrip
      - Gotham:
          quality: 1080p webdl|webrip
      - Great News
      - "Happy!":
          quality: 1080p webdl|webrip
          exact: yes
      - Homeland:
          quality: 1080p webdl|webrip
#      - It's Always Sunny in Philadelphia
      - Kidding:
          quality: 1080p webdl|webrip
      - Last Week Tonight with John Oliver:
          identified_by: ep
      - The Late Show with Stephen Colbert
      - Legion:
          quality: 1080p webdl|webrip
      - Louie:
          quality: 1080p webdl|webrip
      - "Marvel's Agents of S.H.I.E.L.D.":
          quality: 1080p webdl|webrip
      - Modern Family:
          quality: 1080p webdl|webrip
      - "Mr. Robot":
          quality: 1080p webdl|webrip
      - My Little Pony:
          quality: 1080p webdl|webrip
      - Once Upon A Time (2011):
          quality: 1080p webdl|webrip
      - Saturday Night Live:
          quality: 1080p webdl|webrip
      - Sharp Objects:
          quality: 1080p webdl|webrip
          season_packs: only
      - Silicon Valley:
          quality: 1080p webdl|webrip
      - Suits:
          quality: 1080p webdl|webrip
      - The Big Bang Theory:
          quality: 1080p webdl|webrip
      - The Daily Show (with Trevor Noah)
      - The Deuce:
          quality: 1080p webdl|webrip
      #- The Expanse:
      #    quality: 1080p webdl|webrip
      - The Good Place:
          quality: 1080p webdl|webrip
          season_packs: only
          begin: s03e01
      - The Handmaid's Tale:
          quality: 1080p webdl|webrip
#      - The Man in the High Castle:
#          quality: 1080p webdl|webrip
      - The Last Ship:
          quality: 1080p webdl|webrip
      - The Tick
      - The X-Files:
          quality: 1080p webdl|webrip
      - True Detective:
          quality: 1080p webdl|webrip
      - Westworld:
          quality: 1080p webdl|webrip
      - "Who Is America?":
          quality: 1080p webdl|webrip
      
#  #====================
#  #= Template: TV-Shows (internal)
#  #====================
#  tvshows-i:
#    quality: 720p+ hdtv+ h264
#    #trakt_lookup: yes
#    thetvdb_lookup: yes
#    set:
#      path: '/Alexandria/TV-Series/{{series_name}}/Season {{series_season}}'
#      propers: yes
#    series:
#      - Silicon Valley
#      - True Detective
##      - Show Me a Hero

  #====================
  #= Template: Movies
  #====================
  movies:
    quality: 1080p+ bluray h264+
    proper_movies: no
    imdb_lookup: yes
    tmdb_lookup: yes
    thetvdb_lookup: yes
    set:
      path: '/Alexandria/Movies'
    regexp:
      reject:
        - \b3-?D\b: {from: title}                             # Reject 3D versions

  #====================
  #= Template: Sports
  #====================
  sports:
    quality: 720p+ hdtv+ h264
    set:
      path: '/Users/martin/Movies/Sports'
    regexp:
      accept:
        - NFL.*(2014|2015).*(Giants|Jets)
      from: title
  
  #============================
  #= Template: Telegram Message
  #============================
  telegram_msg:
    notify:
      entries:
        template: telegram_msg
        via:
          - telegram:
              bot_token: '{? telegram.bot_token ?}'
              parse_mode: markdown
              recipients:
                - username: '{? telegram.username ?}'


#====================
#= Tasks
#====================
tasks:

  teltest:

    #rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=3c1c3&cats[]=1c1c3&type_origin=1'
    mock:
      - {title: 'Skyscraper.1080p.bluray.x264.dd5.1.group'}

    #quality: 1080p+ bluray+ h264+
    disable:
      - seen

    #accept_all: yes
    regexp:
      accept:
        - 'Skyscraper.*1080p'

    imdb_lookup: yes
    tmdb_lookup: yes

    notify:
      entries:
        template: telegram_msg
        via:
          - telegram:
              bot_token: '{? telegram.bot_token ?}'
              parse_mode: markdown
              recipients:
                - username: '{? telegram.username ?}'


  #====================
  #= Task: TV-Shows from HDBits.org
  #====================
  tvshows-hdbits:
    priority: 10
    rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=3c1c3&cats[]=3c1c6&cats[]=1c1c3&cats[]=2c1c3&cats[]=2c1c6'

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - TV-Shows" >> ~/runlog
      on_output:
        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog
#        for_rejected: echo "- Rejected '{{title}}' Reason={{reason}}" >> ~/runlog
#        for_failed: echo "? Failed '{{title}}' Reason={{reason}}" >> ~/runlog
    
    template:
      - tvshows
      - transmission
      - telegram_msg

#  #====================
#  #= Task: TV-Shows from HDBits.org (internal)
#  #====================
#  tvshows-hdbits-i:
#    priority: 11
#    rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=3c1c3&cats[]=3c1c6&cats[]=1c1c3&cats[]=2c1c3&cats[]=2c1c6&type_origin=1'
#
#    exec:
#      on_start:
#        phase: echo "$(date +'%d/%m %T') - executing task - TV-Shows (internal)" >> ~/runlog
#      on_output:
#        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog
##        for_rejected: echo "- Rejected '{{title}}' Reason={{reason}}" >> ~/runlog
##        for_failed: echo "? Failed '{{title}}' Reason={{reason}}" >> ~/runlog
#    
#    template:
#      - tvshows-i
#      - transmission
#      - telegram_msg

  #====================
  #= Task: Movies from HDBits.org
  #====================
  movies-hdbits:
    priority: 30

    rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=3c1c3&cats[]=1c1c3&type_origin=1'

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Movies" >> ~/runlog
      on_output:
        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog

    imdb_lookup: yes

    #list_queue:
    list_match:
      from:
        - movie_list: movies
    list_add:
      - movie_list: 4k-upgrade

    template:
      - movies
      - transmission
      - telegram_msg

  #====================
  #= Task: Movies from HDBits.org
  #====================
  movies-hdbits-4k-upgrade:
    priority: 32

    rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=1c5c3&cats[]=1c5c5&type_origin=1'

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Movies (4K upgrade)" >> ~/runlog
      on_output:
        for_accepted: echo "+ Notified '{{title}}'" >> ~/runlog

    regexp:
      reject:
        - \b3-?D\b: {from: title}                             # Reject 3D versions
    imdb_lookup: yes
    tmdb_lookup: yes
    thetvdb_lookup: yes

    #list_queue:
    list_match:
      from:
        - movie_list: 4k-upgrade

    quality: 2160p+ remux+ h265+

    template:
      - telegram_msg

  #====================
  #= Task: Movies from HDBits wishlist
  #====================
  movies-hdbits-wishlist:
    priority: 31

#    rss: https://hdbits.org/rss/wishlist?passkey={{ s{ecrets.hdbits.passkey }}
    rss: 'https://hdbits.org/rss/my?passkey={? hdbits.passkey ?}'

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Movies Wishlist" >> ~/runlog
      on_output:
        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog

    proper_movies: no
    imdb_lookup: yes
    tmdb_lookup: yes
    set:
      path: '/Alexandria/Movies'

    template:
      - transmission
      - telegram_msg
    disable:
      - seen
      - seen_info_hash
      - rejected
      - remember_rejected
    accept_all: yes
    no_entries_ok: yes

#  #====================
#  #= Task: Sports from HDBits
#  #====================
#  sports-hdbits:
#    priority: 40
#
#    rss: https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=5c1c3&cats[]=5c1c6
#    exec:
#      on_start:
#        phase: echo "$(date +'%d/%m %T') - executing task - Sports HDBits" >> ~/runlog
#      on_output:
#        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog
#
#    template:
#      - sports
#      - transmission
 

  #====================
  #= Task: Queue movies from IMDB watchlist
  #====================
  queue-imdb:
    priority: 20

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Queue IMDB Watchlist" >> ~/runlog
      on_output:
        for_accepted: echo "+ Added '{{title}}' to queue" >> ~/runlog

#    imdb_list:
#      user_id: ur5604227
#      list: watchlist
#      login: '{? imdb.username ?}'
#      password: '{? imdb.password ?}'
#      list: watchlist

    imdb_watchlist:
      user_id: ur5604227
      list: watchlist

    tmdb_lookup: yes
    imdb_lookup: yes

    template:
      - telegram_msg

    accept_all: yes
    list_add:
      - movie_list: movies


#  #====================
#  #= Task: Sports from HD-SportBits
#  #====================
#  sports-sportbits:
#    priority: 50
#
#    rss: http://hd-sportbits.org/torrentrss.php?rows=10&cat405=1&sou1=1&sou3=1&sou4=1&cod1=1&linktype=dl&passkey=HDSPORTBITSPASSKEY
#    #rss: http://hd-sportbits.org/torrentrss.php?rows=10&cat405=1&med2=1&linktype=dl&passkey=HDSPORTBITSPASSKEY
#
#    exec:
#      on_start:
#        phase: echo "$(date +'%d/%m %T') - executing task - Sports HD-Sportbits" >> ~/runlog
#      on_output:
#        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog
#
#    template:
#      - sports
#      - transmission


#====================
#= Schedules
#====================
schedules:
  - tasks: 'tvshows-hdbits*'
    interval:
      hours: 1
  - tasks: 'movies-hdbits*'
    interval:
      hours: 1
  - tasks: 'movies-hdbits-wishlist'
    interval:
      hours: 1
  - tasks: 'queue-imdb'
#    interval:
#      hours: 24
    schedule:
      hour: 18
      minute: 30
#  - tasks: 'sports-hdbits'
#    interval:
#      hours: 12
#  - tasks: 'sports-sportbits'
#    interval:
#      hours: 12
