#====================
#= Secrets
#====================
variables: secrets.yml

#====================
#= Web UI
#====================
web_server:
  #run_v2: true
  port: 9092

#====================
#= Templates
#====================
templates:

  global:
    verify_ssl_certificates: no

  #====================
  #= Template: Transmission connection settings
  #====================
  transmission:
    transmission:
      host: localhost
      port: 9091
      #username: {? transmission.username ?}
      #password: {? transmission.password ?}
    pathscrub: windows

  #====================
  #= Template: TV-Shows
  #====================
  tvshows:
    quality: 1080p+ webrip+ h264+
    # For 2.18.0
    sort_by:
      field: quality
      reverse: yes
    #trakt_lookup: yes
    thetvdb_lookup: yes
    set:
      path: '/Alexandria/TV-Series/{{series_name}}/Season {{series_season}}'
      propers: yes
    series:
      #- Archer:
      #    quality: webdl|webrip
      - Atlanta:
          quality: webdl|webrip
      - Barry:
          quality: webdl|webrip
      - Brooklyn Nine-Nine:
          quality: webdl|webrip
      - Counterpart:
          quality: webdl|webrip
      - Divorce (2016):
          quality: webdl|webrip
      - "Happy!":
          quality: webdl|webrip
          exact: yes
      - Homeland:
          quality: webdl|webrip
      - "Its Always Sunny in Philadelphia":
          alternate_name: "It's Always Sunny in Philadelphia"
          quality: webdl|webrip
      - Kidding:
          quality: webdl|webrip
      - Last Week Tonight with John Oliver:
          identified_by: ep
      - "Marvel's Agents of S.H.I.E.L.D.":
          quality: webdl|webrip
      - Modern Family:
          quality: webdl|webrip
      - My Little Pony:
          quality: webdl|webrip
      - Rick and Morty:
          quality: webdl|webrip
      - Saturday Night Live:
          quality: 720p+ webdl|webrip
      - The Handmaid's Tale:
          quality: webdl|webrip
      - The Mandalorian:
          quality: 2160p webdl|webrip
      - The Outsider:
          quality: webdl|webrip
      - The Terror:
          quality: webdl|webrip
      - 'True Detective':
          quality: webdl|webrip
      - Watchmen:
          quality: webdl|webrip
      - Westworld:
          quality: webdl|webrip
      - "Who Is America?":
          quality: webdl|webrip

  #====================
  #= Template: Movies
  #====================
  movies:
    quality:
      - 2160p remux|bluray h265+
      - 1080p bluray h264+
    proper_movies: no
    imdb_lookup: yes
    tmdb_lookup: yes
    thetvdb_lookup: yes
    set:
      path: '/Alexandria/Movies'
    regexp:
      reject:
        - \b3-?D\b: {from: title}                             # Reject 3D versions

  #============================
  #= Template: Telegram Message
  #============================
  telegram_msg:
    notify:
      entries:
        template: telegram_msg
        via:
          - telegram:
              bot_token: '{? telegram.bot_token ?}'
              parse_mode: markdown
              disable_previews: yes
              recipients:
                - username: '{? telegram.username ?}'


#====================
#= Tasks
#====================
tasks:

  telegram-test:

    disable: seen

    mock:
      - { title: 'Skyscraper.1080p.bluray.x264.dd5.1-group' }
      - { title: 'Mandy.720p.bluray.x264.dd5.1-group' }
      - { title: 'Mandy.1080p.dvd.x264.dd5.1-group' }

    quality: 1080p bluray

    accept_all: yes

    imdb_lookup: yes
    tmdb_lookup: yes

    notify:
      entries:
        template: telegram_msg
        via:
          - telegram:
              bot_token: '{? telegram.bot_token ?}'
              parse_mode: markdown
              disable_previews: yes
              recipients:
                - username: '{? telegram.username ?}'

  #====================
  #= Task: TV-Shows from HDBits.org
  #====================
  tvshows-hdbits:
    priority: 20
    # 1080p encode/webdl, 4k encode/webdl, all sources
    rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=2c1c3&cats[]=2c1c6&cats[]=2c5c3&cats[]=2c5c6'

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - TV-Shows" >> ~/runlog
      on_output:
        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog
#        for_rejected: echo "- Rejected '{{title}}' Reason={{reason}}" >> ~/runlog
#        for_failed: echo "? Failed '{{title}}' Reason={{reason}}" >> ~/runlog

    template:
      - tvshows
      - transmission
      - telegram_msg

  #====================
  #= Task: Movies from HDBits.org
  #====================
  movies-hdbits:
    priority: 30

    inputs:
        # 4K Remux, all sources
      - rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=1c5c5'
        # 1080p encode/webdl, 4k encode, internal only
      - rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&type_origin=1&cats[]=1c1c3&cats[]=1c1c6&cats[]=1c5c3'

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Movies" >> ~/runlog
      on_output:
        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog

    imdb_lookup: yes

    #list_queue:
    list_match:
      from:
        - movie_list: movies
    if:
      - "'2160p' not in quality":
          list_add:
            - movie_list: 4k-upgrade

    template:
      - movies
      - transmission
      - telegram_msg

  #====================
  #= Task: 4K upgrades from HDBits.org
  #====================
  movies-hdbits-4k-upgrade:
    priority: 31

    # 4K encode/remux, internal only
    rss: 'https://hdbits.org/rss/feed?passkey={? hdbits.passkey ?}&feed=dl&cats[]=1c5c3&cats[]=1c5c5&type_origin=1'

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Movies (4K upgrade)" >> ~/runlog
      on_output:
        for_accepted: echo "+ Notified '{{title}}'" >> ~/runlog

    regexp:
      reject:
        - \b3-?D\b: {from: title}                             # Reject 3D versions
    imdb_lookup: yes
    tmdb_lookup: yes
    thetvdb_lookup: yes

    #list_queue:
    list_match:
      from:
        - movie_list: 4k-upgrade

    quality: 2160p+ remux+ h265+

    template:
      - telegram_msg

  #====================
  #= Task: Movies from HDBits wishlist
  #====================
  movies-hdbits-wishlist:
    priority: 32

    rss: 'https://hdbits.org/rss/my?passkey={? hdbits.passkey ?}'

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Movies Wishlist" >> ~/runlog
      on_output:
        for_accepted: echo "+ Accepted '{{title}}'" >> ~/runlog

    proper_movies: no
    imdb_lookup: yes
    tmdb_lookup: yes
    set:
      path: '/Alexandria/Movies'

    template:
      - transmission
      - telegram_msg
    disable:
      - seen
      - seen_info_hash
      - rejected
      - remember_rejected
    accept_all: yes
    no_entries_ok: yes

  #====================
  #= Task: Remove movies from movie list
  #====================
  prune-imdb:
    priority: 10

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Prune movie list" >> ~/runlog
      on_output:
        for_accepted: echo "- Removed '{{title}}' from list" >> ~/runlog

    movie_list: movies
    crossmatch:
      from:
        - imdb_watchlist:
            user_id: ur5604227
            list: watchlist
      action: reject
      fields: [imdb_id]
    accept_all: yes
    list_remove:
      - movie_list: movies
    seen: no

  #====================
  #= Task: Queue movies from IMDB watchlist
  #====================
  queue-imdb:
    priority: 11

    exec:
      on_start:
        phase: echo "$(date +'%d/%m %T') - executing task - Queue IMDB Watchlist" >> ~/runlog
      on_output:
        for_accepted: echo "+ Added '{{title}}' to queue" >> ~/runlog

    imdb_watchlist:
      user_id: ur5604227
      list: watchlist

    tmdb_lookup: yes
    imdb_lookup: yes

    template:
      - telegram_msg

    accept_all: yes
    list_add:
      - movie_list: movies


#====================
#= Schedules
#====================
schedules:
  - tasks:
      - 'tvshows-hdbits*'
      - 'movies-hdbits*'
      - 'queue-imdb'
      - 'prune-imdb'
    interval:
      hours: 1
